version: '3.8'

services:
  meu-youtube:
    build: .
    container_name: meu-youtube-v2
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
